--
-- PostgreSQL database dump
--

\restrict ZAiZCiKzmi8nxHFx4FyPE3u3yhA36OhjpgdHzxq6KXABzyisRxqqJrmzM09hg1M

-- Dumped from database version 14.20 (Homebrew)
-- Dumped by pg_dump version 14.20 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: items; Type: TABLE; Schema: public; Owner: stationery
--

CREATE TABLE public.items (
    id bigint NOT NULL,
    item_name character varying(255) NOT NULL,
    stock_quantity integer NOT NULL,
    unit_price double precision NOT NULL
);


ALTER TABLE public.items OWNER TO stationery;

--
-- Name: items_id_seq; Type: SEQUENCE; Schema: public; Owner: stationery
--

ALTER TABLE public.items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: request_details; Type: TABLE; Schema: public; Owner: stationery
--

CREATE TABLE public.request_details (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    item_id bigint NOT NULL,
    request_id bigint NOT NULL
);


ALTER TABLE public.request_details OWNER TO stationery;

--
-- Name: request_details_id_seq; Type: SEQUENCE; Schema: public; Owner: stationery
--

ALTER TABLE public.request_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requests; Type: TABLE; Schema: public; Owner: stationery
--

CREATE TABLE public.requests (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    superior_email character varying(255) NOT NULL,
    total_cost double precision,
    requester_id bigint NOT NULL,
    CONSTRAINT requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'WITHDRAWN'::character varying, 'CANCEL_REQUESTED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.requests OWNER TO stationery;

--
-- Name: requests_id_seq; Type: SEQUENCE; Schema: public; Owner: stationery
--

ALTER TABLE public.requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: stationery
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    max_purchase_limit double precision,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['EMPLOYEE'::character varying, 'MANAGER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO stationery;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: stationery
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: stationery
--

COPY public.items (id, item_name, stock_quantity, unit_price) FROM stdin;
1	A4 Notebook	120	2.5
2	Ballpoint Pen Blue	500	0.4
3	Ballpoint Pen Black	480	0.4
4	Stapler Medium	35	6.75
5	Staples Pack 1000	200	1.9
6	Highlighter Yellow	150	0.85
7	Marker Permanent Black	90	1.2
8	Paper Clips Box 100	250	0.7
9	Desk Organizer	25	9.5
10	Sticky Notes 3x3	300	1.1
11	A4 Notebook	120	2.5
12	Ballpoint Pen Blue	500	0.4
13	Ballpoint Pen Black	480	0.4
14	Stapler Medium	35	6.75
15	Staples Pack 1000	200	1.9
16	Highlighter Yellow	150	0.85
17	Marker Permanent Black	90	1.2
18	Paper Clips Box 100	250	0.7
19	Desk Organizer	25	9.5
20	Sticky Notes 3x3	300	1.1
21	Whiteboard Eraser	60	2.2
22	Dry Erase Marker Red	85	1.3
23	Dry Erase Marker Blue	80	1.3
24	USB 32GB	40	12
25	Laptop Stand	15	28
26	Mechanical Pencil 0.7mm	140	1.95
27	Correction Tape	75	2.1
28	Envelope Pack A5 (50)	55	4.8
29	Scissors Large	32	5.4
30	Glue Stick 21g	110	1.05
31	A4 Notebook	120	2.5
32	Ballpoint Pen Blue	500	0.4
33	Ballpoint Pen Black	480	0.4
34	Stapler Medium	35	6.75
35	Staples Pack 1000	200	1.9
36	Highlighter Yellow	150	0.85
37	Marker Permanent Black	90	1.2
38	Paper Clips Box 100	250	0.7
39	Desk Organizer	25	9.5
40	Sticky Notes 3x3	300	1.1
41	Whiteboard Eraser	60	2.2
42	Dry Erase Marker Red	85	1.3
43	Dry Erase Marker Blue	80	1.3
44	USB 32GB	40	12
45	Laptop Stand	15	28
46	Mechanical Pencil 0.7mm	140	1.95
47	Correction Tape	75	2.1
48	Envelope Pack A5 (50)	55	4.8
49	Scissors Large	32	5.4
50	Glue Stick 21g	110	1.05
\.


--
-- Data for Name: request_details; Type: TABLE DATA; Schema: public; Owner: stationery
--

COPY public.request_details (id, quantity, item_id, request_id) FROM stdin;
\.


--
-- Data for Name: requests; Type: TABLE DATA; Schema: public; Owner: stationery
--

COPY public.requests (id, created_date, status, superior_email, total_cost, requester_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: stationery
--

COPY public.users (id, email, full_name, max_purchase_limit, password, role) FROM stdin;
1	jane.doe@college.edu	Jane Doe	900	$2a$10$ouXad7V8lPUGz.k6PMFUreJ.8WZkJ9O4fHq743K..3CsUZUHC19Aq	EMPLOYEE
5	jhonny.doe@college.edu	Jhonny Doe	900	{bcrypt}$2a$10$janehash	EMPLOYEE
6	john.smith@college.edu	John Smith	750	{bcrypt}$2a$10$johnhash	EMPLOYEE
7	mary.jones@college.edu	Mary Jones	2000	{bcrypt}$2a$10$maryhash	MANAGER
8	raj.patel@college.edu	Raj Patel	600	{bcrypt}$2a$10$rajhash	EMPLOYEE
\.


--
-- Name: items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: stationery
--

SELECT pg_catalog.setval('public.items_id_seq', 50, true);


--
-- Name: request_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: stationery
--

SELECT pg_catalog.setval('public.request_details_id_seq', 1, false);


--
-- Name: requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: stationery
--

SELECT pg_catalog.setval('public.requests_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: stationery
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: stationery
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- Name: request_details request_details_pkey; Type: CONSTRAINT; Schema: public; Owner: stationery
--

ALTER TABLE ONLY public.request_details
    ADD CONSTRAINT request_details_pkey PRIMARY KEY (id);


--
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: public; Owner: stationery
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: stationery
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: stationery
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: request_details fk1n5fhf0mnljvaba6rcogg7rjg; Type: FK CONSTRAINT; Schema: public; Owner: stationery
--

ALTER TABLE ONLY public.request_details
    ADD CONSTRAINT fk1n5fhf0mnljvaba6rcogg7rjg FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: request_details fk7siyp69nykrgh6y0lebsx9s0x; Type: FK CONSTRAINT; Schema: public; Owner: stationery
--

ALTER TABLE ONLY public.request_details
    ADD CONSTRAINT fk7siyp69nykrgh6y0lebsx9s0x FOREIGN KEY (request_id) REFERENCES public.requests(id);


--
-- Name: requests fkeoax2t4j9i61p9lmon3009tr4; Type: FK CONSTRAINT; Schema: public; Owner: stationery
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT fkeoax2t4j9i61p9lmon3009tr4 FOREIGN KEY (requester_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict ZAiZCiKzmi8nxHFx4FyPE3u3yhA36OhjpgdHzxq6KXABzyisRxqqJrmzM09hg1M

